name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: gridss/gridss
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # TODO: remove the v from the tag prefix (or change the docker naming convention)
          # TODO: push the correct image. I think it's pushing gridss_export_build_artefacts not gridss
          push: false
          tags: ${{ steps.meta.outputs.tags }}